website/__init__.py
from flask import Flask


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] ='qwerty'
    
    from .views import views 
    
    app.register_blueprint(views,url_prefix= '/')
    
    return app


create_app()

website/views.py
import json
import pickle

from flask import Flask,Blueprint, request, app, jsonify, url_for, render_template
import numpy as np
import pandas as pd

views =Blueprint('views', __name__)


@views.route('/')
def index():
    return render_template('base.html')



house_regmodel = pickle.load(open('./website/House/regmodel.pkl', 'rb'))
house_scalar = pickle.load(open('./website/House/scaling.pkl', 'rb'))

diabetes_classifier = pickle.load(open('./website/Diabetes/d_regmodel.pkl','rb'))
diabetes_scalar = pickle.load(open('./website/Diabetes/d_scaling.pkl', 'rb'))


car_regmodel = pickle.load(open('./website/Car/c_regmodel.pkl','rb'))
car_scalar = pickle.load(open('./website/Car/c_scaling.pkl', 'rb'))

medical_regmodel = pickle.load(open('./website/Medical_Insurance/m_regmodel.pkl','rb'))
medical_scalar = pickle.load(open('./website/Medical_Insurance/m_scaling.pkl', 'rb'))

calorie_regmodel = pickle.load(open('./website/Exercise/e_regmodel.pkl','rb'))
calorie_scalar = pickle.load(open('./website/Exercise/e_scaling.pkl', 'rb'))



@views.route('/House') 
def house():
    return render_template('house.html')

@views.route('/Car') 
def car():
    return render_template('car.html')

@views.route('/Diabetes') 
def diabetes():
    return render_template('diabetes.html')

@views.route('/Medical-Insurance')
def medical_insurance():
    return render_template('medical.html')

@views.route('/Calorie-Predictor')
def calorie_predictor():
    return render_template('exercise.html')


#HOUSE PREDICT API
@views.route('/House/predict_api', methods=['POST'])
def predict_api():
    data = request.json['data']
    print(data)
    print(np.array(list(data.values())).reshape(1, -1))
    new_data = house_scalar.transform(np.array(list(data.values())).reshape(1, -1))
    output = house_regmodel.predict(new_data)
    print(output[0])
    return jsonify(output[0])

# HOUSE PREDICT POST METHOD
@views.route('/predict', methods=['POST'])
def predict():
    data = [float(x) for x in request.form.values()]
    final_input = house_scalar.transform(np.array(data).reshape(1, -1))
    print(final_input)
    output = house_regmodel.predict(final_input)[0]
    output = format(output,".2f")
    return render_template("house.html", prediction_text="The House price prediction is {} Million $".format(output))


#DIABETES PREDICT API
@views.route('/Diabetes/d_predict_api', methods=['POST'])
def d_predict_api():
    data = request.json['data']
    print(data)
    print(np.array(list(data.values())).reshape(1, -1))
    new_data = diabetes_scalar.transform(np.array(list(data.values())).reshape(1, -1))
    output = diabetes_classifier.predict(new_data)
    print(output[0])
    return jsonify(output[0])

# DIABETED PREDICT POST METHOD
@views.route('/d_predict', methods=['POST'])
def d_predict():
    data = [float(x) for x in request.form.values()]
    final_input = diabetes_scalar.transform(np.array(data).reshape(1, -1))
    print(final_input)
    output = diabetes_classifier.predict(final_input)[0] 
    print(output)
    if output == 1:
        return render_template("diabetes.html",prediction_text=" High chances of Diabetes" )
    else:
        return render_template("diabetes.html", prediction_text=" Low chances of Diabetes" )




#CAR PREDICT API
@views.route('/Car/c_predict_api', methods=['POST'])
def c_predict_api():
    data = request.json['data']
    print(data)
    print(np.array(list(data.values())).reshape(1, -1))
    new_data = car_scalar.transform(np.array(list(data.values())).reshape(1, -1))
    output = car_regmodel.predict(new_data)
    print(output[0])
    return jsonify(output[0])


#CAR PREDICT POST METHOD
@views.route('/c_predict', methods=['POST'])
def c_predict():
    data = [float(x) for x in request.form.values()]
    final_input = car_scalar.transform(np.array(data).reshape(1, -1))
    print(final_input)
    output = car_regmodel.predict(final_input)[0] 
    print(output)
    output = format(output,".2f")
    return render_template("car.html", prediction_text="The predicted car price is ₹ {} Lakhs".format(output))


#MEDICAL PREDICT API
@views.route('/Medical/m_predict_api', methods=['POST'])
def m_predict_api():
    data = request.json['data']
    print(data)
    print(np.array(list(data.values())).reshape(1, -1))
    new_data = medical_scalar.transform(np.array(list(data.values())).reshape(1, -1))
    output = medical_regmodel.predict(new_data)
    print(output[0])
    return jsonify(output[0])


#MEDICAL PREDICT POST METHOD
@views.route('/m_predict', methods=['POST'])
def m_predict():
    data = [float(x) for x in request.form.values()]
    final_input = medical_scalar.transform(np.array(data).reshape(1, -1))
    print(final_input)
    output = medical_regmodel.predict(final_input)[0] 
    print(output) 
    output = format(output,".2f")
    return render_template("medical.html", prediction_text="The Medical Insurance predicted  price is ₹ {}".format(output))


#CALORIE PREDICT API
@views.route('/Calorie-Predictor/e_predict_api', methods=['POST'])
def e_predict_api():
    data = request.json['data']
    print(data)
    print(np.array(list(data.values())).reshape(1, -1))
    new_data = calorie_scalar.transform(np.array(list(data.values())).reshape(1, -1))
    output = calorie_regmodel.predict(new_data)
    print(output[0])
    return jsonify(output[0])


#CALORIE PREDICT POST METHOD
@views.route('/e_predict', methods=['POST'])
def e_predict():
    data = [float(x) for x in request.form.values()]
    final_input = calorie_scalar.transform(np.array(data).reshape(1, -1))
    print(final_input)
    output = calorie_regmodel.predict(final_input)[0] 
    print(output) 
    output = format(output,".2f")
    return render_template("exercise.html", prediction_text="Calorie Burnt :  {} Kcal".format(output))

website/templates/car.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Car Price Predictor</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
  </head>

  <body>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <span class="navbar-brand mb-0 h1">Car Prediction</span>
      </div>
    </nav>
    <div class="login">
      <!-- Main Input For Receiving Query to our ML -->
      <form action="{{ url_for('views.c_predict')}}" method="post">
        <input
          type="text"
          name="YEAR1"
          placeholder="YEAR"
          required="required"
        />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"> YEAR of purchase of Car </i></button
        ><br />

        <input type="text" name="PP" placeholder="PP" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">Present Price (in Lakhs) </i></button
        ><br />

        <input type="text" name="KmD" placeholder="KmD" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">KiloMeters Driven </i></button
        ><br />

        <input type="text" name="FT" placeholder="FT" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            >Fuel Type( Petrol:0 , Diesel:1 , CNG : 2)
          </i></button
        ><br />

        <input type="text" name="ST" placeholder="ST" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">
            Seller Type (Dealer:0 , Individual: 1)
          </i></button
        ><br />

        <input type="text" name="TMS" placeholder="TMS" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            >TMS: Transmission Type (Manual:0 , Automatic:1)
          </i></button
        ><br />

        <input type="text" name="OWN" placeholder="OWN" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">OWN: Number of Owners </i></button
        ><br />

        <button type="submit" class="btn btn-primary btn-block btn-large">
          Predict
        </button>
      </form>

      <br />
      <br />
    </div>
    <div class="text">{{prediction_text}}</div>

    <style>
      body {
        background-color: rgb(1, 33, 61);
        font-family: "Trebuchet MS", Verdana, sans-serif;
      }

      .info {
        border: none;
        border-radius: 0 5px 5px 0;
      }

      .info:hover {
        cursor: not-allowed;
      }

      .text {
        margin: 50px 0 20px 395px;
        font-size: 20px;
        font-size: 30px;
        font-weight: bold;
        color: white;
        padding-left: 20px;
      }

      form {
        width: 650px;
        margin: 30px 100px 10px 390px;
        padding: 20px;
        background-color: rgb(224, 124, 2);

        border-radius: 5px;
      }

      input {
        margin: 5px;
        text-align: center;
        border-radius: 5px 0 0 5px;
      }

      .btn {
        height: 50px;
        width: 150px;
        margin: 10px 10px 10px 50px;
        text-align: center;
        font-weight: bolder;
        font-size: 25px;
      }

      button :hover {
        cursor: pointer;
        color: black;
        font-weight: 600;
      }

      .login {
        height: 370px;
        width: 1000px;
        margin-left: 10px 0px 10px 100px;
      }

      .navbar-brand {
        font-size: 28px;
        font-family: "Trebuchet MS", Verdana, sans-serif;
        font-weight: 700;
        margin-bottom: 10px;
      }
    </style>
  </body>
</html>

website/templates/diabetes.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Diabetes Predictor</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
  </head>

  <body>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <span class="navbar-brand mb-0 h1"> Diabetes Prediction </span>
      </div>
    </nav>
    <div class="login">
      <!-- Main Input For Receiving Query to our ML -->
      <form action="{{ url_for('views.d_predict')}}" method="post">
        <input type="text" name="PREG" placeholder="PREG" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">PREG: Number of times pregnant </i></button
        ><br />

        <input type="text" name="GLU" placeholder="GLU" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">GLU: Plasma glucose concentration </i></button
        ><br />

        <input type="text" name="BP2" placeholder="BP" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            >BP: Diastolic blood pressure (mm Hg)</i
          ></button
        ><br />

        <input type="text" name="ST2" placeholder="ST" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            >ST: Triceps skin fold thickness (mm)
          </i></button
        ><br />

        <input
          type="text"
          name="INSULIN2"
          placeholder="INSULIN"
          required="required"
        />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">INSULIN: serum insulin (mu U/ml) </i></button
        ><br />

        <input type="text" name="BMI2" placeholder="BMI" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">BMI: Body mass index </i></button
        ><br />

        <input type="text" name="DPF" placeholder="DPF" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            ><a
              class="link"
              target="”_blank”"
              href="https://openventio.org/wp-content/uploads/Determinants-of-Gestational-Diabetes-Pedigree-Function-for-Pima-Indian-Females-IMOJ-6-121.pdf"
            >
              DPF: Diabetes pedigree function [0-2.5]</a
            >
          </i></button
        ><br />

        <input type="text" name="AGE2" placeholder="AGE" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">AGE: Age (years) </i></button
        ><br />

        <button type="submit" class="btn btn-primary btn-block btn-large">
          Predict
        </button>
      </form>

      <br />
      <br />
    </div>

    <div class="text">{{prediction_text}}</div>

    <style>
      .link {
        color: #1010104d;
        text-decoration: none;
      }

      body {
        background-color: rgb(1, 33, 61);
        font-family: "Trebuchet MS", Verdana, sans-serif;
      }

      .info {
        border: none;
        border-radius: 0 5px 5px 0;
      }

      .info:hover {
        cursor: none;
      }

      .text {
        margin: 70px 0 20px 395px;
        font-size: 20px;
        font-size: 30px;
        font-weight: bold;
        color: white;
        padding-left: 20px;
      }

      form {
        width: 650px;
        margin: 30px 100px 10px 390px;
        padding: 20px;
        background-color: rgb(224, 124, 2);
        border-radius: 5px;
      }

      input {
        margin: 5px;
        text-align: center;

        border-radius: 5px 0 0 5px;
        /* padding: 10px; */
      }

      .btn {
        height: 50px;
        width: 150px;
        margin: 10px 10px 10px 50px;
        text-align: center;
        font-weight: bolder;
        font-size: 25px;
      }

      button :hover {
        cursor: pointer;
        color: black;
        font-weight: 600;
      }

      .login {
        height: 370px;
        width: 1000px;
        margin-left: 10px 0px 10px 100px;
      }

      .navbar-brand {
        font-size: 28px;
        font-family: "Trebuchet MS", Verdana, sans-serif;
        font-weight: 700;
        margin-bottom: 10px;
      }
    </style>
  </body>
</html>

website/templates/exercise.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Calorie Predictor</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
  </head>

  <body>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <span class="navbar-brand mb-0 h1">Calorie Burnt Prediction </span>
      </div>
    </nav>
    <div class="login">
      <!-- Main Input For Receiving Query to our ML -->
      <form action="{{ url_for('views.e_predict')}}" method="post">
        <input
          type="text"
          name="GENDER3"
          placeholder="GENDER"
          required="required"
        />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">GENDER: (Male:0, Female:1)</i></button
        ><br />

        <input type="text" name="AGE3" placeholder="AGE" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">AGE: Age (years) </i></button
        ><br />

        <input
          type="text"
          name="HEIGHT3"
          placeholder="HEIGHT"
          required="required"
        />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">HEIGHT: Height (cm)</i></button
        ><br />

        <input
          type="text"
          name="WEIGHT3"
          placeholder="WEIGHT"
          required="required"
        />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">WEIGHT: Weight (Kg)</i></button
        ><br />

        <input type="text" name="DUR3" placeholder="DUR" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">DUR: Duration of Exercise (min) </i></button
        ><br />

        <input type="text" name="HR3" placeholder="HR" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">HR: Heart Rate (count/min) </i></button
        ><br />
        <input type="text" name="BT3" placeholder="BT" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">BT: BODY TEMPERATURE (&#8451)</i></button
        ><br />

        <button type="submit" class="btn btn-primary btn-block btn-large">
          Predict
        </button>
      </form>

      <br />
      <br />
    </div>
    <div class="text">{{prediction_text}}</div>

    <style>
      .link {
        color: #1010104d;
        text-decoration: none;
      }

      body {
        background-color: rgb(1, 33, 61);
        font-family: "Trebuchet MS", Verdana, sans-serif;
      }

      .info {
        border: none;
        border-radius: 0 5px 5px 0;
      }

      .info:hover {
        cursor: none;
      }

      .text {
        margin: 70px 0 20px 395px;
        font-size: 20px;
        font-size: 30px;
        font-weight: bold;
        color: white;
        padding-left: 20px;
      }

      form {
        width: 650px;
        margin: 30px 100px 10px 390px;
        padding: 20px;
        background-color: rgb(224, 124, 2);
        border-radius: 5px;
      }

      input {
        margin: 5px;
        text-align: center;

        border-radius: 5px 0 0 5px;
        /* padding: 10px; */
      }

      .btn {
        height: 50px;
        width: 150px;
        margin: 10px 10px 10px 50px;
        text-align: center;
        font-weight: bolder;
        font-size: 25px;
      }

      button :hover {
        cursor: pointer;
        color: black;
        font-weight: 600;
      }

      .login {
        height: 370px;
        width: 1000px;
        margin-left: 10px 0px 10px 100px;
      }

      .navbar-brand {
        font-size: 28px;
        font-family: "Trebuchet MS", Verdana, sans-serif;
        font-weight: 700;
        margin-bottom: 10px;
      }
    </style>
  </body>
</html>

website/templates/house.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>ML API</title>
    <link
      href="https://fonts.googleapis.com/css?family=Pacifico"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Arimo"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Hind:300"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
  </head>

  <body>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <span class="navbar-brand mb-0 h1">Boston House Price Prediction </span>
      </div>
    </nav>
    <div class="login">
      <!-- Main Input For Receiving Query to our ML -->
      <form action="{{ url_for('views.predict')}}" method="post">
        <input type="text" name="CRIM" placeholder="CRIM" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            >CRIM - per capita crime rate by town
          </i></button
        ><br />

        <input type="text" name="ZN" placeholder="ZN" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            >ZN - proportion of residential land zoned for lots over 25,000
            sq.ft.
          </i></button
        ><br />
        <input
          type="text"
          name="INDUS"
          placeholder="INDUS"
          required="required"
        />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            >INDUS - proportion of non-retail business acres per town.
          </i></button
        ><br />
        <input type="text" name="CHAS" placeholder="CHAS" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            >CHAS - Charles River dummy variable (1 if tract bounds river; 0
            otherwise)
          </i></button
        ><br />
        <input type="text" name="NOX" placeholder="NOX" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            >NOX - nitric oxides concentration (parts per 10 million)
          </i></button
        ><br />
        <input type="text" name="RM4" placeholder="RM" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            >RM - average number of rooms per dwelling
          </i></button
        ><br />
        <input type="text" name="Age4" placeholder="Age" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            >AGE - proportion of owner-occupied units built prior to 1940
          </i></button
        ><br />
        <input type="text" name="DIS" placeholder="DIS" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            >DIS - weighted distances to five Boston employment centres
          </i></button
        ><br />
        <input type="text" name="RAD" placeholder="RAD" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            >RAD - index of accessibility to radial highways
          </i></button
        ><br />
        <input type="text" name="TAX" placeholder="TAX" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            >TAX - full-value property-tax rate per $10,000
          </i></button
        ><br />
        <input
          type="text"
          name="PTRATIO"
          placeholder="PTRATIO"
          required="required"
        />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            >PTRATIO - pupil-teacher ratio by town
          </i></button
        ><br />
        <input
          type="text"
          name="B"
          placeholder="B"
          required="required"
        /><button type="menu" class="info" disabled>
          <i class="fa fa-search">
            B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
          </i>
        </button>
        <br />
        <input
          type="text"
          name="LSTAT"
          placeholder="LSTAT"
          required="required"
        />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            >LSTAT - % lower status of the population
          </i></button
        ><br />

        <button type="submit" class="btn btn-primary btn-block btn-large">
          Predict
        </button>
      </form>

      <br />
      <br />
    </div>
    <div class="text">{{prediction_text}}</div>

    <style>
      body {
        background-color: rgb(1, 33, 61);
        font-family: "Trebuchet MS", Verdana, sans-serif;
      }
      .info {
        border: none;
        border-radius: 0 5px 5px 0;
      }
      .info:hover {
        cursor: not-allowed;
      }
      .text {
        /* border: 1px solid red; */
        margin: 20px 0 20px 395px;
        font-size: 20px;
        font-weight: bold;
        color: white;
        padding-left: 10px;
      }
      form {
        width: 850px;
        margin: 10px 100px 0 390px;
        padding: 0 20px;
        background-color: rgb(224, 124, 2);
      }
      input {
        margin: 5px;
        text-align: center;

        border-radius: 5px 0 0 5px;
        /* padding: 10px; */
      }
      .btn {
        height: 50px;
        width: 150px;
        margin: 10px 10px 10px 50px;
        text-align: center;
        font-weight: bolder;
        font-size: 25px;
      }
      button :hover {
        cursor: pointer;
        color: black;
        font-weight: 600;
      }
      .login {
        height: 570px;
        width: 1000px;
        margin-left: 10px 0px 10px 100px;
      }
      .navbar-brand {
        font-size: 28px;
        font-family: "Trebuchet MS", Verdana, sans-serif;
        font-weight: 700;
        margin-bottom: 10px;
      }
    </style>
  </body>
</html>

website/templates/medical.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Medical Insurance Predictor</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
  </head>

  <body>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <span class="navbar-brand mb-0 h1">
          Medical Insurance Price Prediction
        </span>
      </div>
    </nav>
    <div class="login">
      <!-- Main Input For Receiving Query to our ML -->
      <form action="{{ url_for('views.m_predict')}}" method="post">
        <input type="text" name="AGE5" placeholder="AGE" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">AGE: Age (years) </i></button
        ><br />

        <input type="text" name="SEX5" placeholder="SEX" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">GENDER: ( Female :0 , Male:1 ) </i></button
        ><br />

        <input type="text" name="BMI5" placeholder="BMI" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">BMI: Body mass index </i></button
        ><br />

        <input
          type="text"
          name="CHILDREN"
          placeholder="CHILDREN"
          required="required"
        />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">CHILDREN: (Number of Childrens) </i></button
        ><br />

        <input
          type="text"
          name="SMOKER"
          placeholder="SMOKER"
          required="required"
        />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search">SMOKE ? : ( Yes: 0 ,No : 1) </i></button
        ><br />

        <input type="text" name="REG5" placeholder="REG" required="required" />
        <button type="menu" class="info" disabled>
          <i class="fa fa-search"
            >REGION: (West:0, East:1, North:2, South:3)</i
          ></button
        ><br />

        <button type="submit" class="btn btn-primary btn-block btn-large">
          Predict
        </button>
      </form>

      <br />
      <br />
    </div>
    <div class="text">{{prediction_text}}</div>

    <style>
      .link {
        color: #1010104d;
        text-decoration: none;
      }

      body {
        background-color: rgb(1, 33, 61);
        font-family: "Trebuchet MS", Verdana, sans-serif;
      }

      .info {
        border: none;
        border-radius: 0 5px 5px 0;
      }

      .info:hover {
        cursor: none;
      }

      .text {
        margin: 70px 0 20px 395px;
        font-size: 20px;
        font-size: 30px;
        font-weight: bold;
        color: white;
        padding-left: 20px;
      }

      form {
        width: 650px;
        margin: 30px 100px 10px 390px;
        padding: 20px;
        background-color: rgb(224, 124, 2);
        border-radius: 5px;
      }

      input {
        margin: 5px;
        text-align: center;

        border-radius: 5px 0 0 5px;
        /* padding: 10px; */
      }

      .btn {
        height: 50px;
        width: 150px;
        margin: 10px 10px 10px 50px;
        text-align: center;
        font-weight: bolder;
        font-size: 25px;
      }

      button :hover {
        cursor: pointer;
        color: black;
        font-weight: 600;
      }

      .login {
        height: 370px;
        width: 1000px;
        margin-left: 10px 0px 10px 100px;
      }

      .navbar-brand {
        font-size: 28px;
        font-family: "Trebuchet MS", Verdana, sans-serif;
        font-weight: 700;
        margin-bottom: 10px;
      }
    </style>
  </body>
</html>